apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: floaty
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - INGRESS_HOST_PLACEHOLDER
      secretName: floaty-tls
  rules:
    - host: INGRESS_HOST_PLACEHOLDER
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: floaty
                port:
                  number: 80
